/**
 * Zustand store — single source of truth for the Studio UI.
 *
 * The store is fed exclusively by WebSocket events (or, in Electron mode,
 * by IPC events relayed from the main process). Components must never
 * call into the bridge directly; they read from the store and let the
 * transport layer push updates.
 *
 * In addition to the bridge-driven world state (agents/tasks/messages),
 * the store now owns Studio-local UI state too:
 *   - displayMode      — Studio Only / Desktop Only / Both toggle
 *   - selectedAgentId  — clicked-agent inspector target
 *   - workspace        — picked folder + scanned info
 *   - chatHistory      — list of past launches
 *   - agentLogs        — synthesized terminal output per agent (mock)
 *   - agentFiles       — synthesized "files touched" per agent (mock)
 *   - mockMode         — true while no real Ruflo is connected
 */

import { create } from 'zustand'

import type {
  AgentInfo,
  AgentMessage,
  AgentType,
  ChatHistoryRecord,
  ProjectSession,
  StudioEvent,
  SwarmInfo,
  TaskInfo,
  WorkspaceInfo,
  WorldSnapshot,
} from '@agent-studio/shared'
import { MAX_MESSAGE_HISTORY } from '@agent-studio/shared'

export type ConnectionStatus = 'idle' | 'connecting' | 'connected' | 'disconnected' | 'error'

/** Toggle states for the display mode segmented control. */
export type DisplayMode = 'studio' | 'desktop' | 'both'

/** Which top-level page is currently visible. */
export type StudioPage = 'office' | 'dashboard'

/** A timestamped event entry rendered by the EventLog panel. */
export interface LoggedEvent {
  /** Monotonic local id; used as a stable React key. */
  id: number
  /** Unix epoch ms when the event was received in the browser. */
  receivedAt: number
  event: StudioEvent
}

/** A line of synthesized terminal output for an agent (mock mode). */
export interface AgentLogLine {
  id: number
  receivedAt: number
  text: string
  /** Coarse log level used by the inspector to color the line. */
  level: 'info' | 'warn' | 'error' | 'success'
}

/** A "file touched" entry for the agent inspector. */
export interface AgentFileEntry {
  id: number
  path: string
  /** What the agent did to this file. */
  kind: 'created' | 'modified' | 'deleted'
}

/** A row in the chat history list. */
export interface ChatHistoryEntry {
  id: number
  prompt: string
  agentCount: number
  strategy: string
  command: string
  /** Generated by the orchestrator so we can correlate live events back. */
  swarmId: string
  status: 'running' | 'completed' | 'failed'
  startedAt: number
  /** Optional message — error string when status === 'failed'. */
  note?: string
}

const MAX_LOGGED_EVENTS = 200
const MAX_AGENT_LOG_LINES = 80
const MAX_AGENT_FILES = 30
const MAX_CHAT_HISTORY = 50

interface StudioState {
  // ── bridge-driven world state ────────────────────────────────────────────
  agents: Map<string, AgentInfo>
  tasks: Map<string, TaskInfo>
  messages: AgentMessage[]
  swarm: SwarmInfo | null
  log: LoggedEvent[]
  connectionStatus: ConnectionStatus
  lastError: string | null
  startedAt: number | null

  // ── studio-local UI state ────────────────────────────────────────────────
  currentPage: StudioPage
  displayMode: DisplayMode
  selectedAgentId: string | null
  workspace: WorkspaceInfo | null
  chatHistory: ChatHistoryEntry[]
  agentLogs: Map<string, AgentLogLine[]>
  agentFiles: Map<string, AgentFileEntry[]>
  mockMode: boolean

  // ── multi-project state ──────────────────────────────────────────────────
  projects: Map<string, ProjectSession>
  activeProjectId: string | null

  // ── actions ──────────────────────────────────────────────────────────────
  setConnectionStatus(status: ConnectionStatus, error?: string | null): void
  hydrateFromSnapshot(snapshot: WorldSnapshot): void
  applyEvent(event: StudioEvent): void
  reset(): void
  setCurrentPage(page: StudioPage): void
  setDisplayMode(mode: DisplayMode): void
  selectAgent(id: string | null): void
  setWorkspace(info: WorkspaceInfo | null): void
  addChatEntry(entry: Omit<ChatHistoryEntry, 'id' | 'startedAt'>): ChatHistoryEntry
  updateChatEntry(id: number, patch: Partial<ChatHistoryEntry>): void
  setMockMode(value: boolean): void
  /** Replace the cached projects list (called on startup after IPC fetch). */
  hydrateProjects(projects: readonly ProjectSession[]): void
  /**
   * Open a workspace — either switches to the matching existing project
   * (restoring its chat history) or creates a new ProjectSession for it.
   * Returns the project id.
   */
  openWorkspace(info: WorkspaceInfo): string
  /** Switch the active project by id, restoring its cached chat history. */
  switchProject(id: string): void
  /** Returns the active project or null if none is open. */
  getActiveProject(): ProjectSession | null
}

let nextLogId = 1
let nextLineId = 1
let nextFileId = 1
let nextChatId = 1

const cloneAgentMap = (state: StudioState): Map<string, AgentInfo> => new Map(state.agents)
const cloneTaskMap = (state: StudioState): Map<string, TaskInfo> => new Map(state.tasks)
const cloneLogsMap = (state: StudioState): Map<string, AgentLogLine[]> =>
  new Map(state.agentLogs)
const cloneFilesMap = (state: StudioState): Map<string, AgentFileEntry[]> =>
  new Map(state.agentFiles)

const pushLogged = (log: LoggedEvent[], event: StudioEvent): LoggedEvent[] => {
  const next: LoggedEvent[] = [{ id: nextLogId++, receivedAt: Date.now(), event }, ...log]
  if (next.length > MAX_LOGGED_EVENTS) next.length = MAX_LOGGED_EVENTS
  return next
}

const appendAgentLog = (
  current: AgentLogLine[] | undefined,
  ...lines: Array<{ text: string; level: AgentLogLine['level'] }>
): AgentLogLine[] => {
  const base = current ?? []
  const next = base.concat(
    lines.map((line) => ({
      id: nextLineId++,
      receivedAt: Date.now(),
      text: line.text,
      level: line.level,
    })),
  )
  if (next.length > MAX_AGENT_LOG_LINES) {
    next.splice(0, next.length - MAX_AGENT_LOG_LINES)
  }
  return next
}

const appendAgentFile = (
  current: AgentFileEntry[] | undefined,
  path: string,
  kind: AgentFileEntry['kind'],
): AgentFileEntry[] => {
  const base = current ?? []
  // Deduplicate — same file shouldn't appear twice consecutively.
  if (base.length > 0 && base[base.length - 1]?.path === path) return base
  const next = base.concat([{ id: nextFileId++, path, kind }])
  if (next.length > MAX_AGENT_FILES) {
    next.splice(0, next.length - MAX_AGENT_FILES)
  }
  return next
}

/** Mock terminal lines per state transition — keeps the inspector lively. */
const generateMockLogLines = (
  agent: AgentInfo,
  newState: AgentInfo['state'],
): Array<{ text: string; level: AgentLogLine['level'] }> => {
  const name = agent.name
  switch (newState) {
    case 'planning':
      return [
        { text: `[${name}] reading task description...`, level: 'info' },
        { text: `[${name}] sketching implementation plan`, level: 'info' },
      ]
    case 'coding':
      return [
        { text: `[${name}] generating module scaffold`, level: 'info' },
        { text: `[${name}] writing handler logic`, level: 'info' },
      ]
    case 'testing':
      return [
        { text: `[${name}] running test suite`, level: 'info' },
        { text: `[${name}] 14 passed, 0 failed`, level: 'success' },
      ]
    case 'communicating':
      return [{ text: `[${name}] composing message to peer`, level: 'info' }]
    case 'blocked':
      return [{ text: `[${name}] waiting on dependency`, level: 'warn' }]
    case 'error':
      return [{ text: `[${name}] encountered an error`, level: 'error' }]
    case 'idle':
      return [{ text: `[${name}] task complete, returning to idle`, level: 'success' }]
    default:
      return []
  }
}

/** Mock file paths per agent type — derived from their archetype. */
const generateMockFiles = (
  agentType: AgentType,
  state: AgentInfo['state'],
): Array<{ path: string; kind: AgentFileEntry['kind'] }> => {
  if (state !== 'coding' && state !== 'testing') return []
  switch (agentType) {
    case 'coder':
      return [
        { path: 'src/routes/handler.ts', kind: 'modified' },
        { path: 'src/middleware/auth.ts', kind: 'created' },
      ]
    case 'tester':
      return [{ path: 'tests/integration/auth.test.ts', kind: 'created' }]
    case 'architect':
      return [{ path: 'docs/architecture.md', kind: 'modified' }]
    case 'researcher':
      return [{ path: 'docs/research-notes.md', kind: 'modified' }]
    case 'coordinator':
      return []
  }
}

export const useStudioStore = create<StudioState>((set, get) => ({
  // bridge state
  agents: new Map(),
  tasks: new Map(),
  messages: [],
  swarm: null,
  log: [],
  connectionStatus: 'idle',
  lastError: null,
  startedAt: null,

  // studio-local UI state
  currentPage: 'office',
  displayMode: 'both',
  selectedAgentId: null,
  workspace: null,
  chatHistory: [],
  agentLogs: new Map(),
  agentFiles: new Map(),
  mockMode: true,

  // multi-project state
  projects: new Map(),
  activeProjectId: null,

  setConnectionStatus(status, error = null) {
    set({ connectionStatus: status, lastError: error })
  },

  hydrateFromSnapshot(snapshot) {
    const agents = new Map<string, AgentInfo>()
    for (const a of snapshot.agents) agents.set(a.id, a)
    const tasks = new Map<string, TaskInfo>()
    for (const t of snapshot.tasks) tasks.set(t.id, t)
    set({
      agents,
      tasks,
      messages: snapshot.messages.slice(-MAX_MESSAGE_HISTORY),
      swarm: snapshot.swarm,
      startedAt: snapshot.swarm?.startedAt ?? null,
    })
  },

  applyEvent(event) {
    const state = get()
    switch (event.type) {
      case 'swarm:initialized': {
        set({
          swarm: event.swarm,
          startedAt: event.swarm.startedAt,
          log: pushLogged(state.log, event),
        })
        return
      }
      case 'swarm:shutdown': {
        const swarm = state.swarm && state.swarm.id === event.swarmId
          ? { ...state.swarm, status: 'shutdown' as const }
          : state.swarm
        set({ swarm, log: pushLogged(state.log, event) })
        return
      }
      case 'agent:spawned': {
        const agents = cloneAgentMap(state)
        agents.set(event.agent.id, event.agent)
        const agentLogs = cloneLogsMap(state)
        agentLogs.set(
          event.agent.id,
          appendAgentLog(state.agentLogs.get(event.agent.id), {
            text: `[${event.agent.name}] spawned (${event.agent.type})`,
            level: 'success',
          }),
        )
        set({ agents, agentLogs, log: pushLogged(state.log, event) })
        return
      }
      case 'agent:state-changed': {
        const existing = state.agents.get(event.agentId)
        if (!existing) {
          set({ log: pushLogged(state.log, event) })
          return
        }
        const updated = { ...existing, state: event.newState }
        const agents = cloneAgentMap(state)
        agents.set(event.agentId, updated)

        // Synthesize terminal output and "files touched" for the inspector.
        const lines = generateMockLogLines(updated, event.newState)
        const fileMutations = generateMockFiles(updated.type, event.newState)
        const reasonLine = event.reason
          ? [{ text: `[${updated.name}] ${event.reason}`, level: 'warn' as const }]
          : []
        const agentLogs = cloneLogsMap(state)
        agentLogs.set(
          event.agentId,
          appendAgentLog(state.agentLogs.get(event.agentId), ...lines, ...reasonLine),
        )

        let agentFiles = state.agentFiles
        if (fileMutations.length > 0) {
          agentFiles = cloneFilesMap(state)
          let nextList = state.agentFiles.get(event.agentId)
          for (const mutation of fileMutations) {
            nextList = appendAgentFile(nextList, mutation.path, mutation.kind)
          }
          if (nextList) agentFiles.set(event.agentId, nextList)
        }

        set({ agents, agentLogs, agentFiles, log: pushLogged(state.log, event) })
        return
      }
      case 'agent:terminated': {
        const agents = cloneAgentMap(state)
        agents.delete(event.agentId)
        // Keep logs/files around so the inspector can still read history.
        set({
          agents,
          // Clear selection if the terminated agent was the inspector target.
          selectedAgentId:
            state.selectedAgentId === event.agentId ? null : state.selectedAgentId,
          log: pushLogged(state.log, event),
        })
        return
      }
      case 'task:started': {
        const tasks = cloneTaskMap(state)
        tasks.set(event.task.id, event.task)
        let agents = state.agents
        if (event.task.assignedAgent) {
          const agent = state.agents.get(event.task.assignedAgent)
          if (agent) {
            agents = cloneAgentMap(state)
            agents.set(agent.id, { ...agent, currentTask: event.task.id })
          }
        }
        // Append the task description to that agent's terminal too.
        let agentLogs = state.agentLogs
        if (event.task.assignedAgent) {
          agentLogs = cloneLogsMap(state)
          agentLogs.set(
            event.task.assignedAgent,
            appendAgentLog(state.agentLogs.get(event.task.assignedAgent), {
              text: `[task] ${event.task.description}`,
              level: 'info',
            }),
          )
        }
        set({ tasks, agents, agentLogs, log: pushLogged(state.log, event) })
        return
      }
      case 'task:completed': {
        const task = state.tasks.get(event.taskId)
        if (!task) {
          set({ log: pushLogged(state.log, event) })
          return
        }
        const tasks = cloneTaskMap(state)
        tasks.set(event.taskId, { ...task, status: 'complete', completedAt: event.timestamp })
        let agents = state.agents
        let agentLogs = state.agentLogs
        if (event.agentId) {
          const agent = state.agents.get(event.agentId)
          if (agent && agent.currentTask === event.taskId) {
            agents = cloneAgentMap(state)
            agents.set(agent.id, { ...agent, currentTask: null })
          }
          if (agent) {
            agentLogs = cloneLogsMap(state)
            agentLogs.set(
              event.agentId,
              appendAgentLog(state.agentLogs.get(event.agentId), {
                text: `[${agent.name}] task completed`,
                level: 'success',
              }),
            )
          }
        }
        // If the completed task corresponds to a chat history entry's swarm,
        // mark that entry as completed (best-effort match by swarmId prefix).
        const updatedHistory = updateChatHistoryStatusForTask(
          state.chatHistory,
          event.taskId,
          'completed',
        )
        set({
          tasks,
          agents,
          agentLogs,
          chatHistory: updatedHistory,
          log: pushLogged(state.log, event),
        })
        return
      }
      case 'task:failed': {
        const task = state.tasks.get(event.taskId)
        if (!task) {
          set({ log: pushLogged(state.log, event) })
          return
        }
        const tasks = cloneTaskMap(state)
        tasks.set(event.taskId, { ...task, status: 'failed', completedAt: event.timestamp })
        let agentLogs = state.agentLogs
        if (event.agentId) {
          const agent = state.agents.get(event.agentId)
          if (agent) {
            agentLogs = cloneLogsMap(state)
            agentLogs.set(
              event.agentId,
              appendAgentLog(state.agentLogs.get(event.agentId), {
                text: `[${agent.name}] task failed: ${event.error}`,
                level: 'error',
              }),
            )
          }
        }
        const updatedHistory = updateChatHistoryStatusForTask(
          state.chatHistory,
          event.taskId,
          'failed',
          event.error,
        )
        set({
          tasks,
          agentLogs,
          chatHistory: updatedHistory,
          log: pushLogged(state.log, event),
        })
        return
      }
      case 'message:sent': {
        const messages = [...state.messages, event.message]
        if (messages.length > MAX_MESSAGE_HISTORY) {
          messages.splice(0, messages.length - MAX_MESSAGE_HISTORY)
        }
        // Append a line to the sender's terminal so it shows up in the inspector.
        const sender = state.agents.get(event.message.fromAgent)
        let agentLogs = state.agentLogs
        if (sender) {
          agentLogs = cloneLogsMap(state)
          agentLogs.set(
            sender.id,
            appendAgentLog(state.agentLogs.get(sender.id), {
              text: `[→ ${event.message.toAgent}] ${event.message.content}`,
              level: 'info',
            }),
          )
        }
        set({ messages, agentLogs, log: pushLogged(state.log, event) })
        return
      }
    }
  },

  reset() {
    set({
      agents: new Map(),
      tasks: new Map(),
      messages: [],
      swarm: null,
      log: [],
      startedAt: null,
      lastError: null,
      selectedAgentId: null,
      agentLogs: new Map(),
      agentFiles: new Map(),
    })
  },

  setCurrentPage(page) {
    set({ currentPage: page })
  },

  setDisplayMode(mode) {
    set({ displayMode: mode })
  },

  selectAgent(id) {
    set({ selectedAgentId: id })
  },

  setWorkspace(info) {
    set({ workspace: info })
  },

  addChatEntry(entry) {
    const created: ChatHistoryEntry = {
      ...entry,
      id: nextChatId++,
      startedAt: Date.now(),
    }
    set((s) => {
      const chatHistory = [created, ...s.chatHistory].slice(0, MAX_CHAT_HISTORY)
      const activeId = s.activeProjectId
      if (!activeId) return { chatHistory }
      const active = s.projects.get(activeId)
      if (!active) return { chatHistory }
      const updatedProject: ProjectSession = {
        ...active,
        lastOpened: Date.now(),
        chatHistory: chatHistoryToRecords(chatHistory),
      }
      const projects = new Map(s.projects)
      projects.set(activeId, updatedProject)
      void persistProject(updatedProject)
      return { chatHistory, projects }
    })
    return created
  },

  updateChatEntry(id, patch) {
    set((s) => {
      const chatHistory = s.chatHistory.map((e) => (e.id === id ? { ...e, ...patch } : e))
      const activeId = s.activeProjectId
      if (!activeId) return { chatHistory }
      const active = s.projects.get(activeId)
      if (!active) return { chatHistory }
      const updatedProject: ProjectSession = {
        ...active,
        chatHistory: chatHistoryToRecords(chatHistory),
      }
      const projects = new Map(s.projects)
      projects.set(activeId, updatedProject)
      void persistProject(updatedProject)
      return { chatHistory, projects }
    })
  },

  setMockMode(value) {
    set({ mockMode: value })
  },

  hydrateProjects(projects) {
    const map = new Map<string, ProjectSession>()
    for (const p of projects) map.set(p.id, p)
    set({ projects: map })
  },

  openWorkspace(info) {
    const id = deriveProjectId(info.path)
    const now = Date.now()
    const existing = get().projects.get(id)
    const chatHistory = existing?.chatHistory ?? []

    const nextProject: ProjectSession = {
      id,
      folderPath: info.path,
      folderName: info.name,
      stack: info.stack,
      gitBranch: info.gitBranch,
      lastOpened: now,
      chatHistory: chatHistory.slice(),
    }
    const projects = new Map(get().projects)
    projects.set(id, nextProject)

    set({
      projects,
      activeProjectId: id,
      workspace: info,
      // Swap the visible chat history to the project's stored history.
      chatHistory: cachedHistoryFromRecords(chatHistory),
    })

    // Mirror out to the bridge for persistence (fire-and-forget).
    void persistProject(nextProject)

    return id
  },

  switchProject(id) {
    const existing = get().projects.get(id)
    if (!existing) return
    const now = Date.now()
    const updated: ProjectSession = { ...existing, lastOpened: now }
    const projects = new Map(get().projects)
    projects.set(id, updated)
    set({
      projects,
      activeProjectId: id,
      workspace: {
        path: existing.folderPath,
        name: existing.folderName,
        fileCount: 0,
        stack: coerceStack(existing.stack),
        gitBranch: existing.gitBranch,
        scannedAt: now,
      },
      chatHistory: cachedHistoryFromRecords(existing.chatHistory),
    })
    void persistProject(updated)
  },

  getActiveProject() {
    const id = get().activeProjectId
    if (!id) return null
    return get().projects.get(id) ?? null
  },
}))

// ── Project persistence helpers ─────────────────────────────────────────────

/** Stable project id derived from a folder path. */
const deriveProjectId = (folderPath: string): string => {
  // Simple DJB2 — collision probability is negligible for per-user folders.
  let hash = 5381
  for (let i = 0; i < folderPath.length; i += 1) {
    hash = ((hash << 5) + hash + folderPath.charCodeAt(i)) | 0
  }
  return `proj-${Math.abs(hash).toString(36)}`
}

/** Coerce a raw stack string (as persisted) back into a WorkspaceStack. */
const coerceStack = (raw: string): WorkspaceInfo['stack'] => {
  if (
    raw === 'node' ||
    raw === 'rust' ||
    raw === 'python' ||
    raw === 'go' ||
    raw === 'ruby' ||
    raw === 'java' ||
    raw === 'unknown'
  ) {
    return raw
  }
  return 'unknown'
}

/**
 * Convert a persisted `ChatHistoryRecord[]` back into the in-memory
 * `ChatHistoryEntry[]` shape. The only difference is type narrowness.
 */
const cachedHistoryFromRecords = (records: readonly ChatHistoryRecord[]): ChatHistoryEntry[] =>
  records.map((r) => ({
    id: r.id,
    prompt: r.prompt,
    agentCount: r.agentCount,
    strategy: r.strategy,
    command: r.command,
    swarmId: r.swarmId,
    status: r.status,
    startedAt: r.startedAt,
    ...(r.note ? { note: r.note } : {}),
  }))

/** Inverse of cachedHistoryFromRecords — strip the in-memory-only fields. */
const chatHistoryToRecords = (entries: readonly ChatHistoryEntry[]): ChatHistoryRecord[] =>
  entries.map((e) => ({
    id: e.id,
    prompt: e.prompt,
    agentCount: e.agentCount,
    strategy: e.strategy,
    command: e.command,
    swarmId: e.swarmId,
    status: e.status,
    startedAt: e.startedAt,
    ...(e.note ? { note: e.note } : {}),
  }))

/** Fire-and-forget mirror to the Electron bridge — safe in browser dev. */
const persistProject = async (project: ProjectSession): Promise<void> => {
  if (typeof window === 'undefined' || !window.studioBridge) return
  try {
    window.studioBridge.saveProject(project)
  } catch {
    // Intentionally swallowed — persistence is best-effort.
  }
}

// ── Helpers used inside applyEvent ─────────────────────────────────────────

const updateChatHistoryStatusForTask = (
  history: ChatHistoryEntry[],
  taskId: string,
  status: 'completed' | 'failed',
  note?: string,
): ChatHistoryEntry[] => {
  // Task IDs from the launch orchestrator look like `${swarmId}-${type}-${i}-task`.
  // We match by checking if the running entry's swarmId is a prefix.
  return history.map((entry) => {
    if (entry.status !== 'running') return entry
    if (!entry.swarmId || !taskId.startsWith(entry.swarmId)) return entry
    return { ...entry, status, ...(note ? { note } : {}) }
  })
}

// ── Selector helpers ─────────────────────────────────────────────────────────

export const selectAgents = (s: StudioState): AgentInfo[] => Array.from(s.agents.values())
export const selectTasks = (s: StudioState): TaskInfo[] => Array.from(s.tasks.values())
export const selectSelectedAgent = (s: StudioState): AgentInfo | null =>
  s.selectedAgentId ? s.agents.get(s.selectedAgentId) ?? null : null
